apiVersion: v1
kind: Pod
metadata:
  labels:
    app: arm-build
  namespace: jenkins
spec:
  securityContext:
    privileged: true
  tolerations:
  - key: node-role.kubernetes.io/knowhere
    operator: "Exists"
    effect: NoSchedule
  - key: "node-role.kubernetes.io/arm"
    operator: "Exists"
    effect: "NoSchedule"
  nodeSelector:
    "kubernetes.io/arch": "arm64"
  enableServiceLinks: false
  containers:
  - name: main
    image: docker:latest
    args: ["sleep", "36000"]
    securityContext:
      privileged: true
    resources:
      limits:
        cpu: "6"
        memory: 12Gi
      requests:
        cpu: "0.5"
        memory: 5Gi
    volumeMounts:
    - mountPath: /var/run
      name: docker-root
    - mountPath: /root/.conan
      name: build-cache
  - name: dind
    image: docker:dind
    securityContext:
      privileged: true
    resources:
      limits:
        cpu: "6"
        memory: 12Gi
      requests:
        cpu: "0.5"
        memory: 5Gi
    volumeMounts:
    - mountPath: /var/run
      name: docker-root
    - mountPath: /root/.conan
      name: build-cache
  volumes:
  - emptyDir: {}
    name: docker-root
  - hostPath:
      path:  /root/.conan
      type: DirectoryOrCreate
    name: build-cache
